-- Adds PlanningWeek.paidAt — separates "locked" (lockWeek, a head-coach
-- sign-off that the planning is ready, no coach-editing restriction yet)
-- from "validated" (validateWeek, which stamps paidAt and marks the week's
-- group classes Fait). Only paidAt being set blocks a coach's own private
-- classes/claims for that week (see lib/planning-lock.ts's isWeekValidated).
--
-- Documentation only, like every migration since 20260904081635_multi_tenant_boxes:
-- tenant tables live in each organization's own "org_<id>" Postgres schema,
-- not "public" (see lib/prisma.ts), so this ALTER was actually applied per
-- existing org schema by a one-off script (mirroring lib/tenant-schema.ts's
-- tenantTableDdl, which is what provisions this column for every *new* org
-- going forward). Keep this file in sync with both.
ALTER TABLE "PlanningWeek" ADD COLUMN "paidAt" TIMESTAMP(3);
